version: '2'
services:
  server:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - VERSION=1.12
  snapshot:
    build: ../snapshots
    volumes:
        - ./backup:/backup
    volumes_from:
        - server
    environment:
        - SNAPSHOT_NAME=minecraft-backup
        - SNAPSHOT_TIMESTAMP_FORMAT=%Y%m%d-%H%M%S
        - SNAPSHOT_INTERVAL=3600
        - SNAPSHOT_MAX_NUM=3
        - SNAPSHOT_LOCATION=/data
        - SNAPSHOT_DESTINATION=/backup
        - SNAPSHOT_METHOD=local         
        - SNAPSHOT_COMPRESSION=zip
  mapgen:
      build: ../minecraft-overviewer
      volumes_from:
          - server
      environment:
          - MINECRAFT_VERSION=1.12
          - MINECRAFT_WORLD_DIR=/data/world
          - MAPGEN_INTERVAL=120