server:
    image: itzg/minecraft-server
    cpu_shares: 480
    mem_limit: 1073741824
    ports:
        - "25565:25565"
    volumes:
        - "/ecs-data/minecraft:/data"
        # - "/data"
    environment:
        EULA: "TRUE"
        OPS: "user"
        WHITELIST: 'user'

mapgen:
    cpu_shares: 300
    mem_limit: 536870912
    image: quay.io/rpcann/minecraft-overviewer
    volumes_from:
        - "server"
    volumes:
        - "/ecs-data/minecraft-web:/home/minecraft/render"
        # - "/home/minecraft/render"
    environment:
        MINECRAFT_WORLD_DIR: "/data/world"
        INTERVAL: 120
        GOOGLE_API_KEY: key

web:
    cpu_shares: 100
    mem_limit: 134217728
    image: quay.io/rpcann/minecraft-hub-web
    ports:
        - "80:80"
    volumes_from:
        - "mapgen"
    environment:
        MAP_DIR: /home/minecraft/render/