##############################################
# docker-compose.yml
# 
# Minecraft Hub
#############################################
version: '2'
services:
    server:
        image: itzg/minecraft-server
        cpu_shares: 480
        mem_limit: 1073741824
        ports:
            - "25565:25565"
        environment:
            - EULA=TRUE
            - VERSION=1.12
            # OPS: ${OPS}
            # WHITELIST: ${WHITELIST}
        env_file:
            - config.env
    snapshot:
        image: quay.io/rpcann/snapshots
        cpu_shares: 100
        mem_limit: 134217728
        volumes:
            - ./backup:/backup
        volumes_from:
            - server
        environment:
            - SNAPSHOT_NAME=minecraft-backup
            - SNAPSHOT_TIMESTAMP_FORMAT=%Y%m%d-%H%M%S
            - SNAPSHOT_INTERVAL=3600
            - SNAPSHOT_MAX_NUM=3
            - SNAPSHOT_LOCATION=/data
            - SNAPSHOT_DESTINATION=/backup
            - SNAPSHOT_METHOD=local         
            - SNAPSHOT_COMPRESSION=zip
        env_file:
            - config.env
    mapgen:
        image: quay.io/rpcann/minecraft-overviewer
        cpu_shares: 300
        mem_limit: 536870912
        volumes_from:
            - server
        environment:
            - MINECRAFT_VERSION=1.12
            - MINECRAFT_WORLD_DIR=/data/world
            - MAPGEN_INTERVAL=120
            # GOOGLE_API_KEY: key
        env_file:
            - config.env
    web:
        image: quay.io/rpcann/minecraft-hub-web
        cpu_shares: 100
        mem_limit: 134217728
        ports:
            - "80:80"
        volumes_from:
            - mapgen
        environment:
            - MAP_DIR=/home/minecraft-overviewer/render/
        env_file:
            - config.env